name: Rust

# Triggers the workflow on push or pull request events
on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Autoconf
      run: autoconf
    - name: Configure
      run: ./configure
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: cargo update
      run: cargo update
    - name: Build after cargo update
      run: cargo build
