name: Rust

# Triggers the workflow on push or pull request events
on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: contains(toJson(github.event.commits), '[skip check]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: autoconf
    - run: ./configure
    - run: cargo build --verbose
    - run: cargo test --verbose
  test_install:
    if: contains(toJson(github.event.commits), '[skip check]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: autoconf
# the prefix is later used for 'make install' (unless using sudo, the
# target directory needs to have normal user write permissions).
    - run: ./configure --prefix=$PWD/install_test
    - run: cargo update

# Now build to make sure a `cargo update` won't change results of the
# build.
    - run: make install
    - run: make uninstall
